import { createApp } from 'vue'
import router from './router'
import App from './App.vue'
import './assets/styles/main.css'
import './assets/styles/scrollbar.css'

// Import Ionicons web components
// For Ionicons v8, we import the component with .js extension
import 'ionicons/components/ion-icon.js'

// Register PWA service worker using vite-plugin-pwa
// The virtual:pwa-register module is auto-generated by vite-plugin-pwa
import { registerSW } from 'virtual:pwa-register'

registerSW({
  onNeedRefresh() {
    // eslint-disable-next-line no-console
    console.info('New content available, please refresh.')
  },
  onOfflineReady() {
    // eslint-disable-next-line no-console
    console.info('App ready to work offline.')
  },
})

// Platform helper (stubbed for web/PWA; expand for native later)
const isNative = () => false

async function bootstrap() {
  try {
    const isDev = import.meta.env.VITE_KALITOSPACE_DEV_MODE === 'true'

    // Info: Using localStorage for browser persistence
    // eslint-disable-next-line no-console
    console.info('Luna web/PWA build ready.')

    // Mount Luna app
    const app = createApp(App)

    app.use(router)

    app.mount('#app')

    // Platform/dev info
    // eslint-disable-next-line no-console
    console.info(`Running on ${isNative() ? 'native platform' : 'web/PWA'}`)
    if (isDev) {
      // eslint-disable-next-line no-console
      console.info('⚙️ Luna is running in dev mode.')
    }

    // Expose dev flags for debugging
    if (isDev) {
      // Add Luna environment info to window
      Object.assign(window, {
        __LUNA_ENV__: { isDev, isNative: isNative },
      })
    }
  } catch (error) {
    // eslint-disable-next-line no-console
    console.error('Failed to bootstrap Luna:', error)
  }
}

// Start the app
bootstrap()
